export const strings = {
  home: {
    title: 'מפקד השיירה',
    tripName: 'צ\'כיה-סלובקיה RV 2026',
    map: 'מפה ומסלול',
    preFlight: 'בדיקה לפני יציאה',
    commander: 'המפקד (AI)',
    meltdown: 'כפתור התמוטטות',
    nextStop: 'תחנה הבאה',
    rvSpecs: 'ממדי הרכב',
    tripOverview: 'סקירת המסלול',
    stops: 'תחנות',
    days: 'ימים',
    viewFullMap: 'לחץ למפה מלאה',
    todayPlan: 'תוכנית להיום',
    weather: 'מזג אוויר',
    budget: 'תקציב והוצאות',
    journal: 'יומן תמונות',
    documents: 'מסמכים',
    checklistWarning: 'הבדיקה לא הושלמה!',
    checklistOk: 'מוכנים ליציאה',
  },
  map: {
    viewEntrance: 'צפייה בכניסה',
    navigate: 'ניווט',
    navigateDrive: 'נווט ברכב',
    navigateHike: 'שבילי הליכה',
    itinerary: 'מסלול הטיול',
    filterAll: 'הכל',
    campsite: 'קמפינג',
    attraction: 'אטרקציה',
    supply: 'אספקה',
    filterByDay: 'סינון לפי יום',
    filterByType: 'סינון לפי סוג',
    travelTime: 'זמן נסיעה',
    minutes: 'דקות',
    km: 'ק"מ',
    calculating: 'מחשב...',
    addStop: 'הוסף תחנה',
    stopName: 'שם התחנה',
    latitude: 'קו רוחב',
    longitude: 'קו אורך',
    day: 'יום',
    type: 'סוג',
    note: 'הערה',
    custom: 'מותאם',
    website: 'אתר',
    heightWarning: 'הגבלת גובה',
    heightToggle: 'הגבלות גובה',
    meters: "מ'",
    heightImpassable: 'לא עביר',
    heightRisky: 'מסוכן',
    rvHeight: 'גובה הרכב',
    loading: 'טוען...',
  },
  checklist: {
    title: 'בדיקה לפני יציאה',
    roofHatch: 'פקק גג סגור',
    stepRetracted: 'מדרגה מקופלת',
    gasOff: 'גז כבוי',
    cabinetsLocked: 'ארונות נעולים',
    greyWaterEmpty: 'מי שפכים ריקים',
    waterFull: 'מיכל מים מלא',
    fridgeOk: 'מקרר עובד',
    tiresOk: 'לחץ צמיגים תקין',
    allDone: 'הכל מוכן ליציאה',
    resetAll: 'אפס הכל',
    completed: 'הושלמו',
    otherRvStatus: 'סטטוס הקרוואן השני',
    readyToRoll: 'מוכן לדרך!',
    notReady: 'עדיין לא מוכן',
    selectRv: 'בחר קרוואן',
    noRvSelected: 'בחר את הקרוואן שלך כדי להתחיל',
  },
  meltdown: {
    button: 'כפתור התמוטטות',
    finding: 'מחפש...',
    playground: 'מגרש משחקים',
    iceCream: 'גלידה',
    lake: 'אגם',
    noResults: 'לא נמצאו תוצאות',
  },
  commander: {
    title: 'המפקד',
    placeholder: 'שאל את המפקד...',
    tripTips: 'טיפים לטיול',
    currencyAlertText: 'עצירה אחרונה בצ\'כיה! כדאי לנצל את הקרונות הצ\'כיות שנשארו לכם לפני המעבר לאירו בסלובקיה.',
    currencyAlertTitle: 'התראת מטבע',
    send: 'שלח',
  },
  today: {
    title: 'תוכנית להיום',
    selectDay: 'בחר יום',
    noStops: 'אין תחנות ליום זה',
    stopOf: 'תחנה',
    nextUp: 'הבא',
    navigateNow: 'נווט עכשיו',
    editPlan: 'ערוך תוכנית',
    donEditing: 'סיום עריכה',
    addItem: 'הוסף פריט',
    time: 'שעה',
    activity: 'פעילות',
    save: 'שמור',
    cancel: 'ביטול',
    editNote: 'ערוך הערה',
    customItem: 'פריט מותאם',
    deleteItem: 'מחק',
    tapToEdit: 'לחץ לעריכה',
    deleteStop: 'הסר תחנה',
    restoreStops: 'שחזר תחנות',
    hiddenCount: 'תחנות מוסתרות',
  },
  weather: {
    title: 'מזג אוויר',
    high: 'גבוה',
    low: 'נמוך',
    rain: 'גשם',
    mm: 'מ"מ',
    forecast: 'תחזית לאזור הבא',
  },
  budget: {
    title: 'תקציב והוצאות',
    addExpense: 'הוסף הוצאה',
    total: 'סה"כ',
    fuel: 'דלק',
    camping: 'קמפינג',
    food: 'אוכל',
    supplies: 'אספקה',
    activity: 'פעילות',
    other: 'אחר',
    amount: 'סכום',
    note: 'הערה',
    day: 'יום',
    noExpenses: 'אין הוצאות עדיין',
    delete: 'מחק',
    converter: 'ממיר מטבעות',
    from: 'מ-',
    to: 'ל-',
    liveRate: 'שער חי',
    rateUnavailable: 'שער לא זמין',
    ils: 'ILS',
  },
  journal: {
    title: 'יומן תמונות',
    takePhoto: 'צלם',
    pickPhoto: 'בחר מגלריה',
    addNote: 'הוסף הערה...',
    noPhotos: 'אין תמונות עדיין',
    save: 'שמור',
    delete: 'מחק',
  },
  documents: {
    title: 'מסמכי נסיעה',
    addDocument: 'הוסף מסמך',
    noDocs: 'אין מסמכים עדיין',
    flight: 'כרטיסי טיסה',
    insurance: 'ביטוח',
    reservation: 'הזמנה',
    rental: 'השכרת רכב',
    passport: 'דרכונים',
    license: 'רישיונות',
    ticket: 'כרטיסי כניסה',
    other: 'אחר',
    note: 'הערה',
    save: 'שמור',
    cancel: 'ביטול',
    delete: 'מחק',
    open: 'פתח',
    category: 'קטגוריה',
    fileName: 'שם קובץ',
    pickFile: 'בחר קובץ',
    saveOffline: 'שמור למצב אופליין',
    cached: 'זמין אופליין',
    removeCached: 'הסר מאופליין',
    viewTicket: 'הצג כרטיס',
    offlineTickets: 'כרטיסים אופליין',
    noTickets: 'אין כרטיסים שמורים',
    cacheAll: 'שמור הכל אופליין',
  },
  liveLocation: {
    shareLocation: 'שתף מיקום',
    stopSharing: 'הפסק שיתוף',
    rv1: 'קרוואן 1',
    rv2: 'קרוואן 2',
    iAm: 'אני נוהג ב...',
    lastUpdate: 'עדכון אחרון',
    locationSharing: 'שיתוף מיקום חי',
    gpsUnavailable: 'GPS לא זמין',
  },
};
