export const strings = {
  common: {
    loading: 'טוען...',
    loadFailed: 'הטעינה נכשלה',
    retry: 'נסה שוב',
  },
  home: {
    title: 'מפקד השיירה',
    tripName: 'צ\'כיה-סלובקיה RV 2026',
    map: 'מפה ומסלול',
    preFlight: 'בדיקה לפני יציאה',
    commander: 'המפקד (AI)',
    meltdown: 'כפתור התמוטטות',
    nextStop: 'תחנה הבאה',
    rvSpecs: 'ממדי הרכב',
    tripOverview: 'סקירת המסלול',
    stops: 'תחנות',
    days: 'ימים',
    viewFullMap: 'לחץ למפה מלאה',
    todayPlan: 'תוכנית להיום',
    weather: 'מזג אוויר',
    budget: 'תקציב והוצאות',
    journal: 'יומן תמונות',
    documents: 'מסמכים',
    notes: 'רשימות והערות',
    checklistWarning: 'הבדיקה לא הושלמה!',
    checklistOk: 'מוכנים ליציאה',
    atGlance: 'מה קורה עכשיו',
    dayOf: 'יום',
    outOf: 'מתוך',
    daysToGo: 'ימים עד היציאה',
    tripEnded: 'הטיול הסתיים',
    stopsToday: 'תחנות היום',
    viewDayPlan: 'לתוכנית המלאה',
  },
  map: {
    viewEntrance: 'צפייה בכניסה',
    navigate: 'ניווט',
    navigateDrive: 'נווט ברכב',
    navigateHike: 'שבילי הליכה',
    itinerary: 'מסלול הטיול',
    filterAll: 'הכל',
    campsite: 'קמפינג',
    attraction: 'אטרקציה',
    supply: 'אספקה',
    filterByDay: 'סינון לפי יום',
    filterByType: 'סינון לפי סוג',
    travelTime: 'זמן נסיעה',
    minutes: 'דקות',
    km: 'ק"מ',
    calculating: 'מחשב...',
    addStop: 'הוסף תחנה',
    stopName: 'שם התחנה',
    latitude: 'קו רוחב',
    longitude: 'קו אורך',
    day: 'יום',
    type: 'סוג',
    note: 'הערה',
    custom: 'מותאם',
    website: 'אתר',
    heightWarning: 'הגבלת גובה',
    heightToggle: 'הגבלות גובה',
    meters: "מ'",
    heightImpassable: 'לא עביר',
    heightRisky: 'מסוכן',
    rvHeight: 'גובה הרכב',
    loading: 'טוען...',
    showFilters: 'הצג מסננים',
    hideFilters: 'הסתר מסננים',
  },
  checklist: {
    title: 'בדיקה לפני יציאה',
    roofHatch: 'פקק גג סגור',
    stepRetracted: 'מדרגה מקופלת',
    gasOff: 'גז כבוי',
    cabinetsLocked: 'ארונות נעולים',
    greyWaterEmpty: 'מי שפכים ריקים',
    waterFull: 'מיכל מים מלא',
    fridgeOk: 'מקרר עובד',
    tiresOk: 'לחץ צמיגים תקין',
    allDone: 'הכל מוכן ליציאה',
    resetAll: 'אפס הכל',
    completed: 'הושלמו',
    otherRvStatus: 'סטטוס הקרוואן השני',
    readyToRoll: 'מוכן לדרך!',
    notReady: 'עדיין לא מוכן',
    selectRv: 'בחר קרוואן',
    noRvSelected: 'בחר את הקרוואן שלך כדי להתחיל',
  },
  meltdown: {
    button: 'כפתור התמוטטות',
    finding: 'מחפש...',
    playground: 'מגרש משחקים',
    iceCream: 'גלידה',
    lake: 'אגם',
    noResults: 'לא נמצאו תוצאות',
  },
  commander: {
    title: 'המפקד',
    placeholder: 'שאל את המפקד...',
    tripTips: 'טיפים לטיול',
    currencyAlertText: 'עצירה אחרונה בצ\'כיה! כדאי לנצל את הקרונות הצ\'כיות שנשארו לכם לפני המעבר לאירו בסלובקיה.',
    currencyAlertTitle: 'התראת מטבע',
    send: 'שלח',
    sosButton: 'SOS חירום',
    sosSearching: 'מחפש עזרה...',
    sosNoGps: 'לא ניתן לאתר מיקום GPS',
    sosError: 'שגיאה בחיפוש עזרה',
    sosTitle: 'מידע חירום',
  },
  today: {
    title: 'תוכנית להיום',
    selectDay: 'בחר יום',
    noStops: 'אין תחנות ליום זה',
    stopOf: 'תחנה',
    nextUp: 'הבא',
    navigateNow: 'נווט עכשיו',
    editPlan: 'ערוך תוכנית',
    donEditing: 'סיום עריכה',
    addItem: 'הוסף פריט',
    time: 'שעה',
    activity: 'פעילות',
    save: 'שמור',
    cancel: 'ביטול',
    editNote: 'ערוך הערה',
    customItem: 'פריט מותאם',
    deleteItem: 'מחק',
    tapToEdit: 'לחץ לעריכה',
    deleteStop: 'הסר תחנה',
    restoreStops: 'שחזר תחנות',
    hiddenCount: 'תחנות מוסתרות',
    emptyDayHint: 'אין תחנות מתוכננות ליום זה. אפשר להוסיף תחנה או פריט משלכם.',
    whatToDo: 'מה עושים',
    whereToSleep: 'איפה ישנים',
    goodToKnow: 'מה כדאי לדעת',
    driveToday: 'נסיעה היום',
    expandAll: 'פתח הכל',
    collapseAll: 'סגור הכל',
  },
  weather: {
    title: 'מזג אוויר',
    high: 'גבוה',
    low: 'נמוך',
    rain: 'גשם',
    mm: 'מ"מ',
    forecast: 'תחזית לאזור הבא',
    offlineHint: 'לא הצלחנו להביא את התחזית. בדקו את החיבור לאינטרנט ונסו שוב.',
    perNight: 'תחזית לכל יום לפי מקום החניה של אותו לילה',
    nightAt: 'לינה',
    secondNight: 'לילה שני באותו קמפינג',
    returnDay: 'יום חזרה, בלי לינה',
    notYetAvailable: 'התחזית ליום הזה עוד לא זמינה — היא נפתחת כשבועיים מראש.',
    coldNight: 'לילה קר, כדאי שק שינה חם',
    heavyRain: 'גשם משמעותי, לקפל סוכך ולאסוף ציוד',
    storm: 'סיכוי לסופות רעמים',
    day: 'יום',
  },
  budget: {
    title: 'תקציב והוצאות',
    addExpense: 'הוסף הוצאה',
    total: 'סה"כ',
    fuel: 'דלק',
    camping: 'קמפינג',
    food: 'אוכל',
    supplies: 'אספקה',
    activity: 'פעילות',
    other: 'אחר',
    amount: 'סכום',
    note: 'הערה',
    day: 'יום',
    noExpenses: 'אין הוצאות עדיין',
    emptyHint: 'הוסיפו הוצאה ראשונה כדי לעקוב אחרי התקציב של השיירה.',
    delete: 'מחק',
    converter: 'ממיר מטבעות',
    from: 'מ-',
    to: 'ל-',
    liveRate: 'שער חי',
    rateUnavailable: 'שער לא זמין',
    ils: 'ILS',
  },
  journal: {
    title: 'יומן תמונות',
    takePhoto: 'צלם',
    pickPhoto: 'בחר מגלריה',
    addNote: 'הוסף הערה...',
    noPhotos: 'אין תמונות עדיין',
    emptyHint: 'העלו תמונה ראשונה כדי להתחיל את יומן הטיול.',
    save: 'שמור',
    delete: 'מחק',
  },
  documents: {
    title: 'מסמכי נסיעה',
    addDocument: 'הוסף מסמך',
    noDocs: 'אין מסמכים עדיין',
    emptyHint: 'העלו דרכונים, ביטוח וכרטיסים כדי שיהיו זמינים גם ללא אינטרנט.',
    flight: 'כרטיסי טיסה',
    insurance: 'ביטוח',
    reservation: 'הזמנה',
    rental: 'השכרת רכב',
    passport: 'דרכונים',
    license: 'רישיונות',
    ticket: 'כרטיסי כניסה',
    other: 'אחר',
    note: 'הערה',
    save: 'שמור',
    cancel: 'ביטול',
    delete: 'מחק',
    open: 'פתח',
    category: 'קטגוריה',
    fileName: 'שם קובץ',
    pickFile: 'בחר קובץ',
    saveOffline: 'שמור למצב אופליין',
    cached: 'זמין אופליין',
    removeCached: 'הסר מאופליין',
    view: 'הצג',
    offlineStatus: 'זמינים אופליין',
    offlineUnavailable: 'המסמך הזה לא נשמר למצב אופליין, ואין כרגע חיבור לאינטרנט. כשתהיה רשת אפשר לפתוח אותו וללחוץ על "שמור למצב אופליין".',
    cacheAll: 'שמור הכל אופליין',
    loadingPdf: 'טוען את המסמך...',
    pdfFailed: 'לא הצלחנו להציג את המסמך כאן.',
  },
  notes: {
    title: 'רשימות והערות',
    subtitle: 'כולם רואים ועורכים את אותו לוח',
    newList: 'רשימה חדשה',
    newNote: 'פתק חדש',
    shoppingList: 'רשימת קניות',
    untitledList: 'רשימה חדשה',
    untitledNote: 'פתק חדש',
    titlePlaceholder: 'כותרת',
    notePlaceholder: 'מה לזכור?',
    addItem: 'הוסף פריט',
    itemPlaceholder: 'פריט חדש',
    pin: 'הצמד למעלה',
    unpin: 'בטל הצמדה',
    color: 'צבע',
    delete: 'מחק',
    confirmDelete: 'למחוק את הפתק?',
    empty: 'הלוח ריק',
    emptyHint: 'צרו רשימת קניות משותפת — כל אחד בשיירה יכול להוסיף ולסמן פריטים.',
    createShoppingList: 'צור רשימת קניות',
    itemsLeft: 'נותרו',
    allDone: 'הכל נאסף',
    pendingSync: 'שינויים ממתינים לסנכרון',
    syncedNow: 'מסונכרן',
    updated: 'עודכן',
  },
  liveLocation: {
    shareLocation: 'שתף מיקום',
    stopSharing: 'הפסק שיתוף',
    rv1: 'קרוואן 1',
    rv2: 'קרוואן 2',
    iAm: 'אני נוהג ב...',
    lastUpdate: 'עדכון אחרון',
    locationSharing: 'שיתוף מיקום חי',
    gpsUnavailable: 'GPS לא זמין',
  },
  offline: {
    offlineReady: 'האפליקציה זמינה אופליין',
    offlineBanner: 'אין חיבור לאינטרנט - מצב אופליין',
    updateAvailable: 'גרסה חדשה זמינה',
  },
  drivingMode: {
    toggle: 'מצב נהיגה',
    on: 'מצב נהיגה פעיל',
    off: 'מצב רגיל',
  },
};
